version: '3.7'

services:

  spacex:
    container_name: spacex
    build:
      context: .
    volumes:
      - './src:/app/src'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
