version: '3.7'

services:

  sample:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/app/src'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
